#############################################################################
# Makefile for building: build/linux/equagen
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Feb 23 14:57:08 2012
# Project:  equagen.pro
# Template: app
# Command: /opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/qmake -spec /opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile equagen.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/linux-g++ -I. -I/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/include/QtCore -I/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/include/QtGui -I/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/include/QtSvg -I/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/lib -lQtSvg -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build.tmp/linux/

####### Files

SOURCES       = main.cxx \
		Document.cxx \
		SvgImage.cxx \
		PngImage.cxx \
		MainWindow.cxx \
		DocumentEditor.cxx \
		Renderer.cxx \
		PlainTextEditor.cxx \
		ErrorLog.cxx \
		BaseImage.cxx \
		SettingsDialog.cxx \
		SettingsProvider.cxx moc_MainWindow.cpp \
		moc_DocumentEditor.cpp \
		moc_PlainTextEditor.cpp \
		moc_ErrorLog.cpp \
		moc_SettingsDialog.cpp \
		qrc_equagen.cpp
OBJECTS       = build.tmp/linux/main.o \
		build.tmp/linux/Document.o \
		build.tmp/linux/SvgImage.o \
		build.tmp/linux/PngImage.o \
		build.tmp/linux/MainWindow.o \
		build.tmp/linux/DocumentEditor.o \
		build.tmp/linux/Renderer.o \
		build.tmp/linux/PlainTextEditor.o \
		build.tmp/linux/ErrorLog.o \
		build.tmp/linux/BaseImage.o \
		build.tmp/linux/SettingsDialog.o \
		build.tmp/linux/SettingsProvider.o \
		build.tmp/linux/moc_MainWindow.o \
		build.tmp/linux/moc_DocumentEditor.o \
		build.tmp/linux/moc_PlainTextEditor.o \
		build.tmp/linux/moc_ErrorLog.o \
		build.tmp/linux/moc_SettingsDialog.o \
		build.tmp/linux/qrc_equagen.o
DIST          = /opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		equagen.pro
QMAKE_TARGET  = equagen
DESTDIR       = build/linux/
TARGET        = build/linux/equagen

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_MainWindow.h ui_DocumentEditor.h ui_ErrorLog.h ui_SettingsDialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) build/linux/ || $(MKDIR) build/linux/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: equagen.pro  /opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/linux-g++/qmake.conf /opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile equagen.pro
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/g++.conf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/common/linux.conf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/mkspecs/linux-g++ CONFIG+=debug -o Makefile equagen.pro

dist: 
	@$(CHK_DIR_EXISTS) build.tmp/linux/equagen1.0.0 || $(MKDIR) build.tmp/linux/equagen1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build.tmp/linux/equagen1.0.0/ && $(COPY_FILE) --parents Document.h SvgImage.h PngImage.h MainWindow.h DocumentEditor.h Renderer.h PlainTextEditor.h ErrorLog.h BaseImage.h SettingsDialog.h SettingsProvider.h build.tmp/linux/equagen1.0.0/ && $(COPY_FILE) --parents equagen.qrc build.tmp/linux/equagen1.0.0/ && $(COPY_FILE) --parents main.cxx Document.cxx SvgImage.cxx PngImage.cxx MainWindow.cxx DocumentEditor.cxx Renderer.cxx PlainTextEditor.cxx ErrorLog.cxx BaseImage.cxx SettingsDialog.cxx SettingsProvider.cxx build.tmp/linux/equagen1.0.0/ && $(COPY_FILE) --parents MainWindow.ui DocumentEditor.ui ErrorLog.ui SettingsDialog.ui build.tmp/linux/equagen1.0.0/ && (cd `dirname build.tmp/linux/equagen1.0.0` && $(TAR) equagen1.0.0.tar equagen1.0.0 && $(COMPRESS) equagen1.0.0.tar) && $(MOVE) `dirname build.tmp/linux/equagen1.0.0`/equagen1.0.0.tar.gz . && $(DEL_FILE) -r build.tmp/linux/equagen1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp moc_DocumentEditor.cpp moc_PlainTextEditor.cpp moc_ErrorLog.cpp moc_SettingsDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_DocumentEditor.cpp moc_PlainTextEditor.cpp moc_ErrorLog.cpp moc_SettingsDialog.cpp
moc_MainWindow.cpp: DocumentEditor.h \
		Document.h \
		SettingsProvider.h \
		SvgImage.h \
		BaseImage.h \
		PngImage.h \
		ui_DocumentEditor.h \
		PlainTextEditor.h \
		Renderer.h \
		ErrorLog.h \
		ui_ErrorLog.h \
		SettingsDialog.h \
		ui_SettingsDialog.h \
		ui_MainWindow.h \
		MainWindow.h
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_DocumentEditor.cpp: Document.h \
		SettingsProvider.h \
		SvgImage.h \
		BaseImage.h \
		PngImage.h \
		ui_DocumentEditor.h \
		PlainTextEditor.h \
		Renderer.h \
		DocumentEditor.h
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) DocumentEditor.h -o moc_DocumentEditor.cpp

moc_PlainTextEditor.cpp: PlainTextEditor.h
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) PlainTextEditor.h -o moc_PlainTextEditor.cpp

moc_ErrorLog.cpp: ui_ErrorLog.h \
		ErrorLog.h
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) ErrorLog.h -o moc_ErrorLog.cpp

moc_SettingsDialog.cpp: SettingsProvider.h \
		ui_SettingsDialog.h \
		SettingsDialog.h
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) SettingsDialog.h -o moc_SettingsDialog.cpp

compiler_rcc_make_all: qrc_equagen.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_equagen.cpp
qrc_equagen.cpp: equagen.qrc \
		templates/equation.template \
		extlib/tango-icon-theme-0.8.90/scalable/actions/edit-copy.svg \
		extlib/tango-icon-theme-0.8.90/scalable/actions/list-add.svg \
		extlib/tango-icon-theme-0.8.90/scalable/actions/media-playback-start.svg \
		extlib/tango-icon-theme-0.8.90/scalable/status/dialog-error.svg
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/rcc -name equagen equagen.qrc -o qrc_equagen.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainWindow.h ui_DocumentEditor.h ui_ErrorLog.h ui_SettingsDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h ui_DocumentEditor.h ui_ErrorLog.h ui_SettingsDialog.h
ui_MainWindow.h: MainWindow.ui
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/uic MainWindow.ui -o ui_MainWindow.h

ui_DocumentEditor.h: DocumentEditor.ui \
		Renderer.h \
		PlainTextEditor.h \
		SvgImage.h \
		BaseImage.h
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/uic DocumentEditor.ui -o ui_DocumentEditor.h

ui_ErrorLog.h: ErrorLog.ui
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/uic ErrorLog.ui -o ui_ErrorLog.h

ui_SettingsDialog.h: SettingsDialog.ui
	/opt/qtsdk-1.1.3/Desktop/Qt/474/gcc/bin/uic SettingsDialog.ui -o ui_SettingsDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build.tmp/linux/main.o: main.cxx MainWindow.h \
		DocumentEditor.h \
		Document.h \
		SettingsProvider.h \
		SvgImage.h \
		BaseImage.h \
		PngImage.h \
		ui_DocumentEditor.h \
		PlainTextEditor.h \
		Renderer.h \
		ErrorLog.h \
		ui_ErrorLog.h \
		SettingsDialog.h \
		ui_SettingsDialog.h \
		ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/main.o main.cxx

build.tmp/linux/Document.o: Document.cxx Document.h \
		SettingsProvider.h \
		SvgImage.h \
		BaseImage.h \
		PngImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/Document.o Document.cxx

build.tmp/linux/SvgImage.o: SvgImage.cxx SvgImage.h \
		BaseImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/SvgImage.o SvgImage.cxx

build.tmp/linux/PngImage.o: PngImage.cxx PngImage.h \
		BaseImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/PngImage.o PngImage.cxx

build.tmp/linux/MainWindow.o: MainWindow.cxx MainWindow.h \
		DocumentEditor.h \
		Document.h \
		SettingsProvider.h \
		SvgImage.h \
		BaseImage.h \
		PngImage.h \
		ui_DocumentEditor.h \
		PlainTextEditor.h \
		Renderer.h \
		ErrorLog.h \
		ui_ErrorLog.h \
		SettingsDialog.h \
		ui_SettingsDialog.h \
		ui_MainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/MainWindow.o MainWindow.cxx

build.tmp/linux/DocumentEditor.o: DocumentEditor.cxx DocumentEditor.h \
		Document.h \
		SettingsProvider.h \
		SvgImage.h \
		BaseImage.h \
		PngImage.h \
		ui_DocumentEditor.h \
		PlainTextEditor.h \
		Renderer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/DocumentEditor.o DocumentEditor.cxx

build.tmp/linux/Renderer.o: Renderer.cxx Renderer.h \
		SvgImage.h \
		BaseImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/Renderer.o Renderer.cxx

build.tmp/linux/PlainTextEditor.o: PlainTextEditor.cxx PlainTextEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/PlainTextEditor.o PlainTextEditor.cxx

build.tmp/linux/ErrorLog.o: ErrorLog.cxx ErrorLog.h \
		ui_ErrorLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/ErrorLog.o ErrorLog.cxx

build.tmp/linux/BaseImage.o: BaseImage.cxx BaseImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/BaseImage.o BaseImage.cxx

build.tmp/linux/SettingsDialog.o: SettingsDialog.cxx SettingsDialog.h \
		SettingsProvider.h \
		ui_SettingsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/SettingsDialog.o SettingsDialog.cxx

build.tmp/linux/SettingsProvider.o: SettingsProvider.cxx SettingsProvider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/SettingsProvider.o SettingsProvider.cxx

build.tmp/linux/moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/moc_MainWindow.o moc_MainWindow.cpp

build.tmp/linux/moc_DocumentEditor.o: moc_DocumentEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/moc_DocumentEditor.o moc_DocumentEditor.cpp

build.tmp/linux/moc_PlainTextEditor.o: moc_PlainTextEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/moc_PlainTextEditor.o moc_PlainTextEditor.cpp

build.tmp/linux/moc_ErrorLog.o: moc_ErrorLog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/moc_ErrorLog.o moc_ErrorLog.cpp

build.tmp/linux/moc_SettingsDialog.o: moc_SettingsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/moc_SettingsDialog.o moc_SettingsDialog.cpp

build.tmp/linux/qrc_equagen.o: qrc_equagen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build.tmp/linux/qrc_equagen.o qrc_equagen.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

